<a href="https://colab.research.google.com/github/AzhagurajaR/mlpw3/blob/main/MLP_Week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from sklearn.datasets import fetch_california_housing

In [ ]:
housing_data = fetch_california_housing()

In [ ]:
type(housing_data)

sklearn.utils.Bunch

In [ ]:
housing_data.data.shape

(20640, 8)

In [ ]:
housing_data.data[:5]

array([[ 8.32520000e+00,  4.10000000e+01,  6.98412698e+00,
         1.02380952e+00,  3.22000000e+02,  2.55555556e+00,
         3.78800000e+01, -1.22230000e+02],
       [ 8.30140000e+00,  2.10000000e+01,  6.23813708e+00,
         9.71880492e-01,  2.40100000e+03,  2.10984183e+00,
         3.78600000e+01, -1.22220000e+02],
       [ 7.25740000e+00,  5.20000000e+01,  8.28813559e+00,
         1.07344633e+00,  4.96000000e+02,  2.80225989e+00,
         3.78500000e+01, -1.22240000e+02],
       [ 5.64310000e+00,  5.20000000e+01,  5.81735160e+00,
         1.07305936e+00,  5.58000000e+02,  2.54794521e+00,
         3.78500000e+01, -1.22250000e+02],
       [ 3.84620000e+00,  5.20000000e+01,  6.28185328e+00,
         1.08108108e+00,  5.65000000e+02,  2.18146718e+00,
         3.78500000e+01, -1.22250000e+02]])

In [ ]:
housing_data.target[:5]

array([4.526, 3.585, 3.521, 3.413, 3.422])

In [ ]:
housing_data.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [ ]:
housing_data.target_names

['MedHouseVal']

In [ ]:
X = pd.DataFrame(housing_data.data, columns=['MedInc','HouseAge','AveRooms','AveBedrms','Population','AveOccup','Latitude','Longitude'])

In [ ]:
X.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [ ]:
y = pd.DataFrame(housing_data.target, columns=['MedHouseVal'])

In [ ]:
y.head()

MedHouseVal
0        4.526
1        3.585
2        3.521
3        3.413
4        3.422

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0, shuffle=False, test_size=0.2)

In [ ]:
X_test.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
16512  2.6368      34.0  5.769022   1.051630      1310.0  3.559783     37.72   
16513  3.6378      17.0  5.432075   1.022642      1802.0  3.400000     37.81   
16514  2.1186      28.0  4.707581   1.039711      1719.0  3.102888     37.80   
16515  2.1250      37.0  4.919431   1.052133       521.0  2.469194     37.80   
16516  2.9950      18.0  4.750988   0.984190      1531.0  3.025692     37.81   

       Longitude  
16512    -121.22  
16513    -121.22  
16514    -121.22  
16515    -121.22  
16516    -121.21

In [ ]:
X_train.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [ ]:
y_train.mean()

MedHouseVal    2.02067
dtype: float64

In [ ]:
y_test.median()

MedHouseVal    2.1475
dtype: float64

In [ ]:
from sklearn.preprocessing import StandardScaler
sscaler = StandardScaler()

In [ ]:
sscaler = sscaler.fit(X_train[['MedInc','HouseAge','AveRooms','AveBedrms','Population','AveOccup','Latitude','Longitude']])

In [ ]:
X_train[['MedInc','HouseAge','AveRooms','AveBedrms','Population','AveOccup','Latitude','Longitude']] = sscaler.transform(X_train[['MedInc','HouseAge','AveRooms','AveBedrms','Population','AveOccup','Latitude','Longitude']])

In [ ]:
X_train.shape

(16512, 8)

In [ ]:
X_train.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  2.417615  0.916627  0.598340  -0.151675   -0.961217 -0.088127  1.258392   
1  2.404898 -0.647225  0.317546  -0.252846    0.830056 -0.174962  1.248807   
2  1.847079  1.776746  1.089176  -0.054970   -0.811298 -0.040064  1.244014   
3  0.984544  1.776746  0.159160  -0.055724   -0.757879 -0.089610  1.244014   
4  0.024444  1.776746  0.334001  -0.040095   -0.751848 -0.161008  1.244014   

   Longitude  
0  -1.611695  
1  -1.606494  
2  -1.616896  
3  -1.622097  
4  -1.622097

In [ ]:
X_test.shape

(4128, 8)

In [ ]:
X_test.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
16512  2.6368      34.0  5.769022   1.051630      1310.0  3.559783     37.72   
16513  3.6378      17.0  5.432075   1.022642      1802.0  3.400000     37.81   
16514  2.1186      28.0  4.707581   1.039711      1719.0  3.102888     37.80   
16515  2.1250      37.0  4.919431   1.052133       521.0  2.469194     37.80   
16516  2.9950      18.0  4.750988   0.984190      1531.0  3.025692     37.81   

       Longitude  
16512    -121.22  
16513    -121.22  
16514    -121.22  
16515    -121.22  
16516    -121.21

In [ ]:
from sklearn.linear_model import LinearRegression
l_reg = LinearRegression()

In [ ]:
l_reg.fit(X_train, y_train)

LinearRegression()

In [ ]:
print(l_reg.coef_)
print(l_reg.intercept_)

[[ 0.83817967  0.12032096 -0.32135834  0.36456599 -0.00170674 -0.04524631
  -0.87994217 -0.82634126]]
[2.02067031]


In [ ]:
sscaler_test = StandardScaler()
sscaler_test = sscaler_test.fit(X_test[['MedInc','HouseAge','AveRooms','AveBedrms','Population','AveOccup','Latitude','Longitude']])
X_test[['MedInc','HouseAge','AveRooms','AveBedrms','Population','AveOccup','Latitude','Longitude']] = sscaler_test.transform(X_test[['MedInc','HouseAge','AveRooms','AveBedrms','Population','AveOccup','Latitude','Longitude']])

In [ ]:
X_test.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  \
16512 -0.763513  0.695039  0.131812  -0.095846   -0.066238  0.011432   
16513 -0.258957 -0.798380 -0.087991  -0.206541    0.420706  0.003761   
16514 -1.024713  0.167950 -0.560608  -0.141360    0.338559 -0.010503   
16515 -1.021487  0.958584 -0.422410  -0.093928   -0.847129 -0.040926   
16516 -0.582962 -0.710532 -0.532292  -0.353370    0.152491 -0.014209   

       Latitude  Longitude  
16512  0.362262   0.086744  
16513  0.418695   0.086744  
16514  0.412424   0.086744  
16515  0.412424   0.086744  
16516  0.418695   0.095090

In [ ]:
y_pred = l_reg.predict(X_test)

In [ ]:
y_pred

array([[ 0.99618196],
       [ 1.21953956],
       [ 0.87591313],
       ...,
       [-0.30616965],
       [-0.10894173],
       [ 0.06820755]])

In [ ]:
pd.DataFrame(y_pred).head()

0
0  0.996182
1  1.219540
2  0.875913
3  0.950028
4  1.042160

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2 = r2_score(y_test, y_pred)
r2

0.6042594181380561

In [ ]:
from sklearn.metrics import mean_squared_error
eval_score = mean_squared_error(y_test, y_pred)
eval_score

0.5766567658315052

In [ ]:
(eval_score)**0.5

0.7593791976552329

In [ ]:
from sklearn.metrics import explained_variance_score
explained_variance_score(y_test, y_pred)

0.6436039146066808

In [ ]:
from sklearn.metrics import max_error
max_error(y_test, y_pred)

5.334573482445463

In [ ]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

0.5647876513323835

In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

0.5766567658315052

In [ ]:
from sklearn.linear_model import SGDRegressor
sgd_reg = SGDRegressor()

In [ ]:
sgd_reg.fit(X_train, y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SGDRegressor()

In [ ]:
print(sgd_reg.intercept_)
print(sgd_reg.coef_)

[2.04515094]
[ 0.86483987  0.21385282 -0.20762742  0.36487737  0.0387894   2.28348078
 -0.72623887 -0.69948763]
